export default {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_CART: "SET_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    FETCH_CARTS: "FETCH_CARTS",
    SET_LOADING: "SET_LOADING",
    ADD_TO_CART_LOADING: "ADD_TO_CART_LOADING",
}
